development:
  adapter: postgresql
  encoding: unicode
  database: library_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: travis_ci_test
  pool: 5
  timeout: 5000
