# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b0067b71b14fe2a003d602ca8eaf8dfbffed8f1906ca836d4b2e484ee6791c1ef4072043351c4dbd01f05f9c14003829e046027c601f9880b2f864e3bedf3bd4
  sorcery_github_callback_url: http://localhost:3000/oauth/callback?provider=github
  sorcery_github_key: <%= ENV["SORCERY_GITHUB_KEY"] %>
  sorcery_github_secret: <%= ENV["SORCERY_GITHUB_SECRET"] %>

  sorcery_twitter_callback_url: http://0.0.0.0:3000/oauth/callback?provider=twitter
  sorcery_twitter_key: <%= ENV["SORCERY_TWITTER_KEY"] %>
  sorcery_twitter_secret: <%= ENV["SORCERY_TWITTER_SECRET"] %>

  sorcery_vk_callback_url: http://localhost:3000/oauth/callback?provider=vk
  sorcery_vk_key: <%= ENV["SORCERY_VK_KEY"] %>
  sorcery_vk_secret: <%= ENV["SORCERY_VK_SECRET"] %>

  sorcery_google_callback_url: http://localhost:3000/oauth/callback?provider=google
  sorcery_google_key: <%= ENV["SORCERY_GOOGLE_KEY"] %>
  sorcery_google_secret: <%= ENV["SORCERY_GOOGLE_SECRET"] %>

test:
  secret_key_base: c980e3c75f232b13a2460b1486e0cee0842a812303c6894f7f004f028be848ecbe85843b61f6cf0ce9086146d006222f2c0ef9902caaecd7a7409ee7223bb679
  sorcery_github_key: <%= ENV["SORCERY_GITHUB_KEY"] %>
  sorcery_github_secret: <%= ENV["SORCERY_GITHUB_SECRET"] %>

  sorcery_twitter_key: <%= ENV["SORCERY_TWITTER_KEY"] %>
  sorcery_twitter_secret: <%= ENV["SORCERY_TWITTER_SECRET"] %>

  sorcery_vk_key: <%= ENV["SORCERY_VK_KEY"] %>
  sorcery_vk_secret: <%= ENV["SORCERY_VK_SECRET"] %>

  sorcery_google_key: <%= ENV["SORCERY_GOOGLE_KEY"] %>
  sorcery_google_secret: <%= ENV["SORCERY_GOOGLE_SECRET"] %>
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  sorcery_github_callback_url: <%= ENV["SORCERY_GITHUB_CALLBACK_URL"] %>
  sorcery_github_key: <%= ENV["SORCERY_GITHUB_KEY"] %>
  sorcery_github_secret: <%= ENV["SORCERY_GITHUB_SECRET"] %>
  
  sorcery_twitter_callback_url: http://0.0.0.0:3000/oauth/callback?provider=twitter
  sorcery_twitter_key: <%= ENV["SORCERY_TWITTER_KEY"] %>
  sorcery_twitter_secret: <%= ENV["SORCERY_TWITTER_SECRET"] %>

  sorcery_vk_callback_url: http://localhost:3000/oauth/callback?provider=vk
  sorcery_vk_key: <%= ENV["SORCERY_VK_KEY"] %>
  sorcery_vk_secret: <%= ENV["SORCERY_VK_SECRET"] %>

  sorcery_google_callback_url: http://localhost:3000/oauth/callback?provider=google
  sorcery_google_key: <%= ENV["SORCERY_GOOGLE_KEY"] %>
  sorcery_google_secret: <%= ENV["SORCERY_GOOGLE_SECRET"] %>
